# Generated by Django 5.0.4 on 2024-05-06 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('cognom', models.CharField(max_length=100)),
                ('edat', models.CharField(max_length=100)),
                ('correu', models.CharField(max_length=100)),
                ('assignatures', models.CharField(max_length=200)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LRR_centre.rol')),
            ],
        ),
    ]
